# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: '0'
        - name: git
          run: |
            git --version
            git config user.name "GitHub Actions Bot"
            git config user.email "odyn@gmail.com"
            git commit --allow-empty -m "undetected"
            git push origin main
